"""DSDL → C++ types, generated by nunavut as a build action."""

load("@rules_cc//cc:defs.bzl", "cc_library")

def dsdl_cc_library(name, namespace, root, deps = [], **kwargs):
    """Generates C++ types for a DSDL root namespace and exposes them as a cc_library.

    Args:
      name: Library name.
      namespace: The root namespace's .dsdl files.
      root: The root namespace directory name, e.g. "uavcan".
      deps: Libraries the generated headers depend on.
      **kwargs: Forwarded to the cc_library.
    """
    headers = name + "_headers"
    _dsdl_headers(
        name = headers,
        namespace = namespace,
        root = root,
    )
    cc_library(
        name = name,
        hdrs = [":" + headers],
        includes = [headers],
        deps = deps,
        **kwargs
    )

def _dsdl_headers_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name)

    # pydsdl resolves symlinks, so give it a real copy of the namespace tree.
    ctx.actions.run_shell(
        command = """
            set -e
            staging=$(mktemp -d)
            cp -rL "$1" "$staging/$2"
            "$3" --target-language cpp --language-standard c++20 --experimental-languages \
                --allow-unregulated-fixed-port-id --outdir "$4" "$staging/$2"
        """,
        arguments = [
            _root_dir(ctx.files.namespace[0], ctx.attr.root),
            ctx.attr.root,
            ctx.executable._nnvg.path,
            out.path,
        ],
        inputs = ctx.files.namespace,
        tools = [ctx.executable._nnvg],
        outputs = [out],
        mnemonic = "Nunavut",
        progress_message = "Generating DSDL types for %{label}",
    )
    return [DefaultInfo(files = depset([out]))]

def _root_dir(dsdl_file, root):
    prefix, _, _ = dsdl_file.path.partition("/" + root + "/")
    return prefix + "/" + root

_dsdl_headers = rule(
    implementation = _dsdl_headers_impl,
    attrs = {
        "namespace": attr.label(allow_files = [".dsdl"], mandatory = True),
        "root": attr.string(mandatory = True),
        "_nnvg": attr.label(
            default = "//bazel:nnvg",
            executable = True,
            cfg = "exec",
        ),
    },
)
